package com.cube.chat.dao;

import com.cube.chat.pojo.ChatRecord;
import com.cube.chat.pojo.ChatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int countByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int deleteByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int insertSelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    List<ChatRecord> selectByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    ChatRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatRecord record);
}